config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "top#index"
  resources :groups, except: [:show,:destroy,:index] do
    resources :messages, only: [:index, :create]
  end
  resources :users, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates_presence_of :name
  has_many :users, through: :group_users
  has_many :group_users
  has_many :messages
  accepts_nested_attributes_for :group_users
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates_presence_of :body, if: "image.blank?"
  mount_uploader :image, ImageUploader
  scope :after_id, -> (last_message_id) { where( "id > ?", last_message_id ) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups, through: :group_users
  has_many :group_users

  scope :other_users, ->(current_user) { where.not(id: current_user.id) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :set_group_new, only: [:new, :create]
  before_action :set_group_update, only: [:edit, :update]

  def new
  end

  def index
    @groups = current_user.groups
  end

  def ajax_user_list
    @user = User.where('name LIKE ?', "%#{params[:user_name]}%")
    render 'user_list', formats: [:json], handlers: [:jbuilder]
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_messages_path(@group), notice: 'グループが作成されました'
    else
      flash.now[:alert] = 'グループ名を入力してください'
      render action: :new
    end
  end

  def edit
    @group = Group.find(params[:id])
    @other_users = @group.users.other_users(current_user)
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループが更新されました'
    else
      flash.now[:alert] = 'グループが更新されませんでした'
      render edit_group_path(@group)
    end

  end

  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group_new
    @group = Group.new
    @users = User.all
  end

  def set_group_update
    @group = Group.find(params[:id])
    @users = User.all
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  before_action :set_messages
  def index
    @group = Group.find(params[:group_id])
    @message = Message.new
    @groups = current_user.groups
    @add_messages = @group.messages.after_id(params[:last_message_id])
    respond_to do |format|
      format.html
      format.json { render "update_message.json.jbuilder" }
    end
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path, notice: 'メッセージが投稿されました'}
        format.json { render "message_index.json.jbuilder" }
      end
    else
      @group = Group.find(params[:group_id])
      flash.now[:alert] = 'メッセージを入力してください'
      render action: :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:body, :image).merge(group_id: params[:group_id], user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_messages
    @messages = @group.messages.includes(:user)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
    @user = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.where('name LIKE ?', "%#{params[:user_name]}%")
    render 'user_list', formats: [:json], handlers: [:jbuilder]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for(@group) do |f|
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, 'グループ名', class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, value: @group.name , id: "chat_group_name", class: "chat-group-form__input"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, "チャットメンバーを追加", class: "chat-group-form__label"
    .chat-group-form__field--right
      = text_field_tag :name,'', placeholder: "追加したいユーザー名を入力してください", id: 'keyword', class: 'chat-group-form__input'
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--search.clearfix
      .chat-group-form__field--left
        = f.label :name, "追加したいメンバーを選択", class: "chat-group-form__label"
      .chat-group-form__field--right.margin-top
        %ul.clearfix
          #user-list.clearfix
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, "チャットメンバー", class: "chat-group-form__label"
    .chat-group-form__field--right.clearfix
      %ul.clearfix.chat-group-form__field
        .field-input.clearfix
          %input{ name: "group[user_ids][]", type: "hidden", value: "#{current_user.id}" }
            %p.chat-group-form__field.chat-group-user
              #{current_user.name}
            - if @other_users
              - @other_users.each do |user|
                .chat-group-form__field.clearfix
                  %li.join-user
                    %input{ name: "group[user_ids][]", type: "hidden", value: "#{user.id}" }
                    %p.chat-group-user
                      #{user.name}
                      %a.remove-user 削除
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right.clearfix
      = f.submit "Save", class: "chat-group-form__action-btn", disable_with: "save"

app/views/groups/_group.html.haml
%form#edit_chat_group_22.edit_chat_group{"accept-charset" => "UTF-8", :action => "/chat_groups/22", :method => "post"}
    %input{:name => "utf8", :type => "hidden", :value => "✓"}/
    %input{:name => "_method", :type => "hidden", :value => "patch"}/
    %input{:name => "authenticity_token", :type => "hidden", :value => "U5ABp0/UobRQTSwsR0V40bX1w3t0rZ0CTqrVyLecD+L6sdhBRO/gVcKy7w/Rgxnc7Hf0Ts39996dal3to5fTag=="}/
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_name"} グループ名
      .chat-group-form__field--right
        %input#chat_group_name.chat-group-form__input{:name => "chat_group[name]", :placeholder => "グループ名を入力してください", :type => "text", :value => "ほげー"}/
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        %input.chat-group-form__action-btn{"data-disable-with" => "Save", :name => "commit", :type => "submit", :value => "Save"}/

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: "form"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ作成
  = render partial: "form"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content:"text/html; charset=UTF-8", http: { equiv: "Content-Type" }}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
  - flash.each do |key, value|
    = content_tag(:div, value, class: "#{key}")
  = yield

app/views/messages/_message.html.haml
.ajax-chatspace{'data-message_id': message.id }
  %p.chatspace-tweet-username
    = message.user.name
  %p.chatspace-tweet-time
    = message.created_at.strftime("%Y-%m-%d %H:%M:%S")
  %p.chatspace-tweet-text
    = message.body
  .chatspace-tweet-image
    = image_tag(message.image)

app/views/messages/_user-groups.html.haml
.group-info
  %p.group-info__name
    = group.name
  %p.group-info__comment
    -if group.messages.present?
     = group.messages.last.body
    - else
      まだ新着メッセージがありません

app/views/messages/index.html.haml
.display
  .header
    .header__message
      チャットグループが作成されました。
  .left-contents
    .left-content-top
      .left-content-top__name
        #{current_user.name}
      = link_to edit_user_registration_path do
        = fa_icon 'cog 2x'
      = link_to new_group_path do
        = fa_icon 'pencil-square-o 2x'
    .group-info
      .group-info__name
        lipton
      .group-info__comment
        カロリーメイト
  .right-contents
    .right-content-top
      .edit-btn
        = link_to 'EDIT', edit_group_path(@group),class: 'edit'
      .right-content-top-group-name
        グリコ
      .right-content-user-name
        ポッキー
    .chatspace
      =render partial: 'message', collection: @messages
    .chatspace-footer
      = form_for ([@group,@message]), html: { class: 'js-form' } do |f|
        = f.text_field :body, placeholder: "type a message", class: "text-field"
        = f.submit "SEND", class: "send-btn"
        = f.file_field :image, style: "display: none;", id: "image_input_origin"
        = fa_icon("image 2x", id: "image_input",class: 'fa-file-image-o')

app/views/top/index.html.haml
.display
  .header
    .header__message
      チャットグループが作成されました。
  .left-contents
    .left-content-top
      .left-content-top__name
        %h2= current_user.name
      = link_to edit_user_registration_path do
        = fa_icon 'cog 2x'
      = link_to new_group_path do
        = fa_icon 'pencil-square-o 2x'
    .group-info
      .group-info__name
        lipton
      .group-info__comment
        カロリーメイト
  .right-contents
    .right-content-top
      .edit-btn
        = link_to 'EDIT', edit_group_path(id:1),class: 'edit'
      .right-content-top-group-name
        グリコ
      .right-content-user-name
        ポッキー
    .chatspace
      .chatspace-tweet-username
        サンビーム
      .chatspace-tweet-time
        yyyy/mm/dd hh:mm:ss
      .chatspace-tweet-text
        グルービー！！
      .chatspace-tweet-username
        ウマゴン
      .chatspace-tweet-time
        yyyy/mm/dd hh:mm:ss
      .chatspace-tweet-text
        メルメルメー！！
    .chatspace-footer
      = form_tag('', method: :post) do
        = text_field_tag :text, "", class: 'text-field', placeholder: 'type a message'
        = submit_tag 'SEND', class: "send-btn"
        = link_to "/chatspace" do
          = fa_icon 'file-image-o'